# /*********************************************************************
# ** Program name: Read and Sort
# ** Author: Ethan Dunham
# ** Date: 3/3/17
# ** Description: This is the makefile for read and sort
# *********************************************************************/

readSort: 
	g++ -std=c++0x main.cpp -o readSort

clean:
	$(RM) *.o readSort
