# /*********************************************************************
# ** Program name:DiceWar
# ** Author: Ethan Dunham
# ** Date: 1/28/17
# ** Description: This is the makefile for diceWar
# *********************************************************************/
dice: 
	g++ -std=c++11 Main.cpp Game.cpp Die.cpp LoadedDie.cpp -o dice
clean:
	$(RM) *.o dice
