# /*********************************************************************
# ** Program name: RPG
# ** Author: Ethan Dunham
# ** Date: 3/20/17
# ** Description: This is the makefile for RPG
# *********************************************************************/

RPG: 
	g++ -std=c++11 main.cpp ChestSquare.cpp VampireSquare.cpp KeySquare.cpp Square.cpp Space.cpp MonsterSquare.cpp DoorSquare.cpp Player.cpp TrapSquare.cpp WallSquare.cpp -o RPG
clean:
	$(RM) *.o RPG
