# /*********************************************************************
# ** Program name: nodes
# ** Author: Ethan Dunham
# ** Date: 2/17/17
# ** Description: This is the makefile for nodes
# *********************************************************************/

nodes: 
	g++ nodes.cpp -o nodes
clean:
	$(RM) *.o nodes
