# /*********************************************************************
# ** Program name:Determinant Calculator
# ** Author: Ethan Dunham
# ** Date: 1/15/17
# ** Description: This is the makefile for Determinant Calculator
# *********************************************************************/
# 	basic makefile.
#	g++ is the compiler.
#	-o sets the executible name
#
#	Edit the following as so:
# 	program		-	the name of your executable.
# 	file1.cpp	-	whatever your source files are. add more as needed.
# 	file1.hpp	-	whatever your headers are (if any), add more as needed.
#
#	type "make" or "make default" in terminal to use the makefile.
determinantCalc:
	g++ determinant.cpp readMatrix.cpp mainCalculator.cpp -o determinantCalc
clean:
	$(RM) *o determinantCalc