# /*********************************************************************
# ** Program name:The Ants Go Marching
# ** Author: Ethan Dunham
# ** Date: 1/22/17
# ** Description: This is the makefile for ants
# *********************************************************************/
ants: 
	g++ antMain.cpp Ant.cpp menu.cpp verification.cpp -o ants
clean:
	$(RM) *o ants