# /*********************************************************************
# ** Program name: Queue
# ** Author: Ethan Dunham
# ** Date: 02/24/17
# ** Description: This is the makefile for Queue
# *********************************************************************/

queue: 
	g++ -std=c++0x menu.cpp Queue.cpp -o queue

clean:
	$(RM) *.o queue
