# /*********************************************************************
# ** Program name: recursive examples
# ** Author: Ethan Dunham
# ** Date: 2/8/17
# ** Description: This is the makefile for recursive examples
# *********************************************************************/

recursive: 
	g++ -std=c++11 Source.cpp -o recursive
clean:
	$(RM) *.o recursive
