# /*********************************************************************
# ** Program name: RPG Game
# ** Author: Ethan Dunham
# ** Date: 2/12/17
# ** Description: This is the makefile for RPGGame
# *********************************************************************/

RPGGame: 
	g++ -std=c++11 main.cpp Vampire.cpp Barbarian.cpp HarryPotter.cpp BlueMen.cpp Creature.cpp Medusa.cpp  -o RPGGame

clean:
	$(RM) *.o RPGGame
