# /*********************************************************************
# ** Program name:Palindrome and Queue
# ** Author: Ethan Dunham
# ** Date: 3/8/17
# ** Description: This is the makefile for Palindrome and Queue
# *********************************************************************/

palinqueue: 
	g++ main.cpp Stack.cpp -o palinqueue

clean:
	$(RM) *.o palinqueue
