# /*********************************************************************
# ** Program name:School Database
# ** Author: Ethan Dunham
# ** Date: 2/2/17
# ** Description: This is the makefile for lab 4.
# *********************************************************************/
database: 
	g++ -std=c++11 main.cpp University.cpp Person.hpp Student.cpp Teacher.cpp Building.cpp -o database

clean:
	$(RM) *.o database
